# Generated by Django 5.0.3 on 2024-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes',
            field=models.FileField(blank=True, upload_to='module_notes/'),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
