# Generated by Django 5.0.3 on 2024-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_module_notes_module_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
