# Generated by Django 5.0.3 on 2024-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_usercourseaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapecourse',
            name='image',
        ),
        migrations.AddField(
            model_name='scrapecourse',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
